In [46]:
import numpy as np
from numpy import cos, sin, degrees, radians
import modern_robotics as mr

## Calculate bList for manipulator

In [16]:
blist = np.array([])

joint1b = np.array([[0.0, 0.0, 0.0, 0.766, 0.000, -0.6428]])
joint2b = np.array([[0.0, 0.0, 1.0, 0.0, 0.3904, 0.0]])
joint3b = np.array([[0.0, 1.0, 0.0, 0.032, 0.000, -0.424]])
joint4b = np.array([[0.0, 1.0, 0.0, 0.016, 0.000, -0.240]])



In [35]:
blist = np.concatenate((joint1b, joint2b, joint3b, joint4b), axis=0).T

## Manipulator at rest

In [18]:
M0e = mr.RpToTrans(R=np.array([[0.766, 0, 0.6428], [0, 1, 0],[-0.6428, 0, 0.766]]).T,
                    p= [0.3904, 0, 0.5371])

In [57]:
M0e

array([[ 0.766 ,  0.    , -0.6428,  0.3904],
       [ 0.    ,  1.    ,  0.    ,  0.    ],
       [ 0.6428,  0.    ,  0.766 ,  0.5371],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [86]:
Tbc = mr.RpToTrans(R=np.array([[1,0,0],[0,1,0],[0,0,1]]).T,
                   p=[0.18, 0.0, 0.065])
Tcb = mr.TransInv(Tbc)
Pco = [0.20, 0.00, 0.05]
angle = 45 * 2*np.pi / 360
Toe_grip = mr.RpToTrans(R=np.array([[cos(angle), 0, sin(angle)], [0, 1, 0], [-sin(angle), 0, cos(angle)]]),
                        p=[0, 0, 0])
Rco = np.array([[cos(angle), 0, sin(angle)], [0, 1, 0], [-sin(angle), 0, cos(angle)]])  # mr.TransToRp(Toe_grip)
Tco_desired = mr.RpToTrans(R=Rco, p=Pco)

In [87]:
Tco_desired.round(4)

array([[ 0.7071,  0.    ,  0.7071,  0.2   ],
       [ 0.    ,  1.    ,  0.    ,  0.    ],
       [-0.7071,  0.    ,  0.7071,  0.05  ],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [88]:
Tbo_desired = Tbc @ Tco_desired

In [89]:
Tbo_desired = Tbo_desired.round(decimals=5)

In [90]:
# Initial guess
thetalist0 = (0, 0, 0, 0)

In [91]:
%%time
thetalist, success = mr.IKinBody(Blist=blist,
                                 M=M0e,
                                 T=Tbo_desired,
                                 thetalist0=thetalist0,
                                 eomg=0.02,   # 0.08 rad = 5 deg uncerainty
                                 ev=0.025)
print(success)
print(thetalist)
print(degrees(thetalist[2]))
print(degrees(thetalist[3]))

True
[-6.97831596e-02 -3.76474589e-17  6.03938963e-01  8.79628961e-01]
34.60315365571535
50.39902699728704
Wall time: 14.4 ms


In [83]:
thetalist.round(4)

array([-0.0079,  0.    ,  0.7038,  1.5652])

In [43]:
success

True

In [39]:
thetalist

array([ 1.40101480e-01,  2.43906762e-16,  1.03271000e+00, -1.90533657e+00])